spring:
  profiles.active : dev 
  mvc.throw-exception-if-no-handler-found: true
  resources.add-mappings: false
  messages.basename : i18n/messages , i18n/ValidationMessages, i18n/errors
  messages.fallback-to-system-locale : false
  messages.encoding: UTF-8
  mvc.locale : en
  boot.admin.url: http://localhost:8080
--- 

spring: 
  profiles: dev
  datasource.url : jdbc:hsqldb:mem:testdb
  datasource.driverClassName : org.hsqldb.jdbc.JDBCDriver 
  datasource.username : sa
  datasource.password :
  jpa.database-platform : org.hibernate.dialect.HSQLDialect
  jpa.hibernate.ddl-auto : create-drop
  h2.console.enabled: true
  h2.console.path: /console
  jpa.show-sql : true
  devtools.restart.enabled : true
  thymeleaf.cache: false
  application.admin.enabled : true

---

spring:
  profiles: production
  datasource.url : jdbc:mysql://localhost:3306/quickpoll?autoReconnect=true&useSSL=false
  datasource.username : root
  datasource.password : root
  datasource.driver-class-name: com.mysql.jdbc.Driver
  jpa.properties.hibernate.dialect : org.hibernate.dialect.MySQL5Dialect
  jpa.hibernate.ddl-auto : create-drop
  datasource.testWhileIdle : true
  datasource.validationQuery : SELECT 1
  jpa.show-sql : true
  jpa.hibernate.naming-strategy : org.hibernate.cfg.ImprovedNamingStrategy
  devtools.restart.enabled : false
--- 

spring: 
  profiles: h2db
  datasource.url : jdbc:h2:~/testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
  datasource.driverClassName : org.h2.Driver
  datasource.username : sa
  datasource.password :
  jpa.database-platform : org.hibernate.dialect.H2Dialect
  jpa.hibernate.ddl-auto : create-drop
  jpa.show-sql : true
  devtools.restart.enabled : true
  
--- 

spring: 
  profiles: HSQLDB
  datasource.url : jdbc:hsqldb:file:F:\DATABASE\quickpoll\testdb
  datasource.driverClassName : org.hsqldb.jdbc.JDBCDriver
  datasource.username : sa
  datasource.password :
  jpa.database-platform : org.hibernate.dialect.HSQLDialect
  jpa.hibernate.ddl-auto : create-drop
  jpa.show-sql : true
  devtools.restart.enabled : true
---
logging:
  level.org.hibernate.SQL: debug
